// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/games/LinuxQuiz.tsx": () => import("../components/mockups/games/LinuxQuiz.tsx"),
  "./components/mockups/games/SQLQuiz.tsx": () => import("../components/mockups/games/SQLQuiz.tsx"),
  "./components/mockups/games/TypingGame.tsx": () => import("../components/mockups/games/TypingGame.tsx")
};
